@startuml
Class Document {
 integer id
 String name
 Date create
 Group group
 Student student
}
Class DocumentPersistency {
 Document Document
}
Class Student{
 integer ra
 String name
 String email
 String password
}
Document - Group: belong >
DocumentPersistency o-- Document: contain >
Document - Student: association >
@enduml