@startuml
Class Professor {
 string name
 string email
 string username
 string password
 string courseResponsability
}
Class ProfessorPersistency {
 void crud()
}
ProfessorPersistency ..> Professor
@enduml