@startuml
Class Document {
 integer id
 String name
 Date create
 Group group
 Student student
 integer score
}

Class Student {
 integer ra
 String name
 String email
 String password
}
Class StudentPersistency {
  void crud()
}
Class Group {
 integer id
 String name
}
Class GroupPersistency {
  void crud()
}
Document - Group: belong >
Item -- Group: belong >
GroupPersistency ..> Group
DocumentPersistency ..> Document
Document -- Student: association >
StudentPersistency ...> Student
@enduml